### ISSUE TITLE
Nano Not updating

### ISSUE THREAD

**Issue by adamtz** [pastudan/altfolio-live#4]
Possibly due to CMC changing their listing of NANO from XRB to NANO

**Comment by dada1134** [comment]
You have to use NANO instead of XRB. XRB is still there but doesn't get upated.

**Comment by pastudan** [comment]
@dada1134 is correct, NANO is the new ticker symbol on CMC, and since your portfolio is keyed off of XRB, it wasn't updating.

I just now made it update all your XRB to NANO if you hadn't already added any NANO to your portfolio. https://github.com/pastudan/altfolio-live/commit/eed3498cb01242e201e4fa04ead9411acbd992cb#diff-14b1e33d5bf5649597cdc0e4f684daddR48
